apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kogito-kafka
  namespace: appdev-aiml-demo
spec:
  kafka:
    version: 2.5.0
    replicas: 1
    listeners:
      external:
        type: route
      plain:
        authentiation:
          type: scram-sha-512
      tls:
        authentiation:
          type: tls
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: '2.5'
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 90
    userOperator:
      reconciliationIntervalSeconds: 120
